name: odoo_employee
description: "Odoo Employee App"
publish_to: 'none' # Remove if you want to publish on pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  convert: ^3.1.1
  dart_jsonwebtoken: ^2.7.1
  xml_rpc: ^0.4.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0   

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon2.png"